source 'https://rubygems.org'                            

gem 'awestruct', '>= 0.5.3'                               
gem 'rake', '>= 0.9.2'                                   
gem 'kramdown', '>= 0.14.2'   
gem 'git'
